language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - 'docker build --tag fastsolve/desktop:16.04 --tag fastsolve/desktop:latest . &&
     docker push fastsolve/desktop && touch succeed'
  - 'cat succeed && git clone -b dev git@github.com:fastsolve/docker-desktop.git dev &&
     cd dev &&
     docker build --tag fastsolve/desktop:dev . &&
     docker push fastsolve/desktop:dev && touch succeed'
  - 'cat succeed && git clone -b debug git@github.com:fastsolve/docker-desktop.git debug &&
     cd debug &&
     docker build --tag fastsolve/desktop:debug . &&
     docker push fastsolve/desktop:debug'
  - docker images
