language: python

services: docker

env: BRANCH=dev

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - 'docker build --tag fastsolve/desktop:$BRANCH
                  --build-arg SSHKEY_ID=$SSHKEY_ID
                  --build-arg MFILE_ID=$MFILE_ID . &&
     docker push fastsolve/desktop &&
     touch success'
# Trigger build of ci-dev branch of numgeom-desktop
  - '[[ ! -f success ]] ||
     (git clone -b ci-dev https://$GIT_USER:$GIT_TOKEN@github.com/numgeom/docker-desktop.git numgeom 2> /dev/null &&
      cd numgeom &&
      git commit --allow-empty -m "Trigger compilation." &&
      git push && cd ..)'
# Test scripts
  - '[[ ! -f success ]] ||
    (git clone -b master https://github.com/fastsolve/docker-desktop.git master &&
     master/fastsolve_desktop.py -d -n -t $BRANCH && docker stop $(docker ps -q) &&
     master/fastsolve_jupyter.py -d -n -t $BRANCH && docker stop $(docker ps -q))'
  - docker images
