language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - 'docker build --tag fastsolve/desktop:dev-env . &&
     docker push fastsolve/desktop:dev-env &&
     touch success'
# Test startup scripts and trigger build of dev branch
  - '[[ ! -f success ]] ||
       (git clone -b ci-dev https://$GIT_USER:$GIT_TOKEN@github.com/fastsolve/docker-desktop.git ci-dev &&
       cd ci-dev &&
       git commit --allow-empty -m "Trigger compilation." &&
       git push)'
# Test scripts
  - '[[ ! -f success ]] ||
    (git clone -b master https://github.com/fastsolve/docker-desktop.git master &&
     master/fastsolve_desktop.py -d -n -t dev-env && docker stop $(docker ps -q) &&
     master/fastsolve_jupyter.py -d -n -t dev-env && docker stop $(docker ps -q))'
  - docker images
