language: python

services: docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  - 'docker build --tag fastsolve/desktop:dev . &&
     docker push fastsolve/desktop:dev &&
     touch success'
# Trigger build of debug branch
  - 'cat success &&
     git clone -b debug https://$GIT_USER:$GIT_TOKEN@github.com/fastsolve/docker-desktop.git debug 2> /dev/null &&
     cd debug &&
     git commit --allow-empty -m "Trigger compilation." &&
     git push'
  - docker images
